name=lib_avr
version=0.1.0
author=Microcontroller-Oscilloscope
maintainer=Camren Chraplak
sentence=This library has the core functionality needed for each avr board for the Microcontroller-Oscilloscope project
paragraph=
category=
url=https://github.com/Microcontroller-Oscilloscope/lib_avr
architectures=
includes=board.h
